package http

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"sort"
	"testing"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/claudioed/network-inventory-planning/internal/application/usecases"
)

// openAPISchemas loads components.schemas from apis/openapi.yaml.
func openAPISchemas(t *testing.T) map[string]map[string]any {
	t.Helper()
	raw, err := os.ReadFile("../../../../apis/openapi.yaml")
	if err != nil {
		t.Fatalf("read openapi.yaml: %v", err)
	}
	var doc struct {
		Components struct {
			Schemas map[string]map[string]any `yaml:"schemas"`
		} `yaml:"components"`
	}
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse openapi.yaml: %v", err)
	}
	return doc.Components.Schemas
}

func schemaKeys(t *testing.T, schemas map[string]map[string]any, name string) (props []string, required []string, schema map[string]any) {
	t.Helper()
	schema, ok := schemas[name]
	if !ok {
		t.Fatalf("openapi.yaml has no schema %q", name)
	}
	p, _ := schema["properties"].(map[string]any)
	for k := range p {
		props = append(props, k)
	}
	if r, ok := schema["required"].([]any); ok {
		for _, v := range r {
			required = append(required, v.(string))
		}
	}
	sort.Strings(props)
	sort.Strings(required)
	return props, required, schema
}

func jsonKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// TestSimulationResponseMatchesTheOpenAPISchema is the sensor for a contract
// escape: the spec (and the console's types, generated by hand from it) once
// described GET /v1/transfer-simulations as {asOf, options[]} while the handler
// served {advisory, asOf, sites[]}, so a consumer written to the spec could
// never work against the service. The live response's property names must equal
// the schema's, at the top level and for the site items, and every `required`
// property must be present.
func TestSimulationResponseMatchesTheOpenAPISchema(t *testing.T) {
	h := Handler{Simulate: &usecases.SimulateTransferOptions{
		Snapshot:     stubSnapshotRepo{facts: stubFacts()},
		MaxStaleness: time.Hour,
		Now:          simNow,
	}}
	rec := httptest.NewRecorder()
	h.Routes().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/v1/transfer-simulations", nil))
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d: %s", rec.Code, rec.Body.String())
	}
	var body map[string]any
	if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
		t.Fatal(err)
	}

	schemas := openAPISchemas(t)
	props, required, _ := schemaKeys(t, schemas, "SimulationResponse")
	if got := jsonKeys(body); !equalStrings(got, props) {
		t.Fatalf("response keys %v != SimulationResponse properties %v", got, props)
	}
	for _, r := range required {
		if _, ok := body[r]; !ok {
			t.Errorf("required property %q missing from the response", r)
		}
	}

	sites, ok := body["sites"].([]any)
	if !ok || len(sites) == 0 {
		t.Fatalf("response has no sites to check: %v", body["sites"])
	}
	siteProps, siteRequired, _ := schemaKeys(t, schemas, "SiteSimulation")
	site := sites[0].(map[string]any)
	if got := jsonKeys(site); !equalStrings(got, siteProps) {
		t.Fatalf("site keys %v != SiteSimulation properties %v", got, siteProps)
	}
	for _, r := range siteRequired {
		if _, ok := site[r]; !ok {
			t.Errorf("required site property %q missing from the response", r)
		}
	}
}
