{{- if and .Values.analytics.enabled .Values.analytics.projector.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "network-inventory-planning.projectorFullname" . }}
  labels:
    {{- include "network-inventory-planning.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics-projector
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "network-inventory-planning.projectorFullname" . }}
  minReplicas: {{ .Values.analytics.projector.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.analytics.projector.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.analytics.projector.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.analytics.projector.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- if and .Values.analytics.enabled .Values.analytics.reports.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "network-inventory-planning.reportsFullname" . }}
  labels:
    {{- include "network-inventory-planning.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics-reports
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "network-inventory-planning.reportsFullname" . }}
  minReplicas: {{ .Values.analytics.reports.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.analytics.reports.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.analytics.reports.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.analytics.reports.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
