apiVersion: v1
kind: Service
metadata:
  name: {{ include "network-inventory-planning.fullname" . }}
  labels:
    {{- include "network-inventory-planning.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "network-inventory-planning.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
