import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerate with: npm run clean-api-docs && npm run gen-api-docs
import apiSidebar from './docs/api-reference/rest/sidebar';

/**
 * Explicit sidebar (the fleet convention: no autogenerated sidebars).
 * Overview, Operations, Development, Domain-Driven Design, Ecosystem,
 * AI Ecosystem (MCP), API Reference, Architecture Decision Records.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/introduction'},
      items: ['overview/architecture', 'overview/quickstart'],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {type: 'doc', id: 'operations/runbook'},
      items: [
        'operations/configuration',
        'operations/observability',
        'operations/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: ['development/testing'],
    },
    {
      type: 'category',
      label: 'Domain-Driven Design',
      link: {type: 'doc', id: 'ddd/subdomain-classification'},
      items: [
        'ddd/use-cases',
        'ddd/domain-events',
        'ddd/ubiquitous-language',
        {
          type: 'category',
          label: 'DDD artifacts (ddd-crew)',
          items: [
            'ddd/core-domain-chart',
            'ddd/bounded-context-canvas',
            'ddd/context-map',
            'ddd/aggregate-design-canvas',
            'ddd/domain-message-flow',
            'ddd/eventstorming',
            'ddd/class-diagram',
            'ddd/entity-relationship',
            'ddd/sequence-diagrams',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      link: {type: 'doc', id: 'ecosystem/integration'},
      items: [],
    },
    {
      type: 'category',
      label: 'AI Ecosystem (MCP)',
      items: ['mcp/tools'],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/overview'},
      items: [...apiSidebar],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {type: 'doc', id: 'adr/about'},
      items: [
        'adr/0001-network-inventory-planning-boundary',
        'adr/0002-phase1-read-models-and-simulation',
        'adr/0003-transfer-saga',
        'adr/0004-cloudevents-type-catalogue',
        'adr/0005-work-demand-release-and-fact-transitions',
        'adr/0006-migrations-over-a-direct-connection',
        'adr/0007-phase4-observability-and-scheduled-runs',
        'adr/0008-transfer-read-side-and-read-only-mcp',
        'adr/0009-analytics-read-side',
        'adr/0010-console-remote-nip-mfe',
        'adr/0011-godog-bdd-acceptance-tests',
        'adr/0012-otlp-telemetry-export',
      ],
    },
  ],
};

export default sidebars;
